# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
    - package-ecosystem: 'npm'
      directories:
          - '/'
          - '/data/zip-download'
      schedule:
          interval: 'weekly'
          day: 'tuesday'
          time: '03:00'
          timezone: 'Europe/London'
      assignees: ['cmenon12']
      labels:
          - 'dependencies'
      open-pull-requests-limit: 5
      rebase-strategy: 'auto'
      commit-message:
          include: 'scope'
          prefix: ''
      groups:
          minor-updates:
              patterns:
                  - '*'
              update-types:
                  - 'minor'
      ignore:
          # Ignore all patch updates
          - dependency-name: '*'
            update-types: ['version-update:semver-patch']
          # Ignore node versions
          - dependency-name: 'node'
          - dependency-name: '@types/node'
          # Ignore 4.x of zod for now, as openai requires 3.x
          # See PRs #18 and #20 when re-enabling
          - dependency-name: 'zod'
            versions: ['4.x']
    - package-ecosystem: 'github-actions'
      directory: '/'
      schedule:
          interval: 'weekly'
          day: 'tuesday'
          time: '03:00'
          timezone: 'Europe/London'
      assignees: ['cmenon12']
      labels:
          - 'dependencies'
      open-pull-requests-limit: 5
      rebase-strategy: 'auto'
