# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
    - package-ecosystem: 'npm'
      directories:
          - '/'
          - '/data/zip-download'
      schedule:
          interval: 'daily'
          time: '03:00'
          timezone: 'Europe/London'
      labels:
          - 'dependencies'
      cooldown:
          default-days: 3
      commit-message:
          prefix: ''
          include: 'scope'
      groups:
          patch-updates:
              patterns:
                  - '*'
              update-types:
                  - 'patch'
      ignore:
          - dependency-name: 'node'
          - dependency-name: '@types/node'
          - dependency-name: '@x-govuk/govuk-prototype-filters'
            # 2.0.0 requires Node.js v22, we currently use v20.
            versions: ['2.x']
    - package-ecosystem: 'github-actions'
      directory: '/'
      schedule:
          interval: 'daily'
          time: '03:00'
          timezone: 'Europe/London'
      labels:
          - 'dependencies'
