name: Bug report
description: Report a bug or problem with the application
labels: [bug]

body:
    - type: textarea
      id: description
      attributes:
          label: Describe the bug
          description: A clear and concise description of what the bug is, and why it's a problem.
      validations:
          required: true

    - type: textarea
      id: steps
      attributes:
          label: Steps to reproduce
          description: List the steps to reproduce the behaviour. Include any unique database/environment setup.
          placeholder: |
              1. Go to...
              2. Click on...
              3. See error
      validations:
          required: true

    - type: textarea
      id: fix
      attributes:
          label: How should the bug be fixed?
          description: If you're not sure, feel free to say so and leave this blank.

    - type: input
      id: os
      attributes:
          label: Device, OS and browser used
          description: State the device, its operating system, and the browser used when the bug was found.

    - type: textarea
      id: context
      attributes:
          label: Additional context (if applicable)
          description: Add any other context about the problem here.

    - type: textarea
      id: screenshots
      attributes:
          label: Screenshots (if applicable)
          description: Add screenshots to help explain your problem.
