blank_issues_enabled: false
contact_links:
    - name: Contact the maintainers
      url: https://forms.office.com/e/bctaftxd8h
      about: Use this form to contact the maintainers, e.g., if you've found a security issue
